### PR TITLE
Fix default settings not being applied

### LINKED ISSUE #73: `0.3.7-rc0` does not work with `wlan0`, only `eth0`
Hi!

Following up on https://github.com/nerves-project/nerves_examples/pull/85#issue-186513505 here as it pertains to this repo.

`0.3.7-rc0` seems to work correctly with `eth0` but not with `wlan0`. The fix to have it work was to use `0.3`. I tested with (rpi3) and `0.3.6` works correctly, so it stopped working in the current `.7-rc0`.

cc: @deanchouinard, @ConnorRigby

### PR DESCRIPTION
**Pull request by ConnorRigby**
This fixes the `default:` config.exs option not working.

Fixes #73

### CODE REVIEW

**Comment by fhunleth** [comment]
Could you squash the intermediate commits to make this easier to review?

**Comment by ConnorRigby** [comment]
I thought i did that already. :+1: :hourglass:

**Comment by fhunleth** [comment]
Thanks for breaking the big changes out into separate PRs. I rebased this branch with what was left.

File: lib/nerves_network/config.ex [hunk 1]
```diff
@@ -46,8 +46,8 @@ defmodule Nerves.Network.Config do
     {:noreply, s}
   end
 
-  def update(old, old, _) do
-    {old, []}
+  def update(old, old) do
```
Comment (fhunleth) [inline lib/nerves_network/config.ex]: Oh my!

**Comment by ConnorRigby** [comment]
Commit message updated.
